kind: pipline
name: Winsper-Server

steps:
- name: test
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - mvn clean
  - mvn package -Dmaven.test.skip=true
  - echo "test and package server completed 🙂🙂🙂"

- name: upload
  image: appleboy/drone-scp
  settings:
    host: 10.0.0.98
    username: root
    key:
      from_secret: private_key
    rm: true
    target: /root/test/Winsper/server
    source:
    - target/winsper-server-0.0.1-SNAPSHOT.jar
    - Dockerfile

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 10.0.0.98
    username: root
    key:
      from_secret: private_key
    command_timeout: 10m
    script:
    - cd /root/test/Winsper/server/target
    - cp ../Dockerfile .
    - docker rm -f winsper-server
    - docker stack rm testwinsper
    - docker network rm testwinsper_network
    - docker build -t winsper-server .
    - docker stack deploy -c /root/test/Winsper/docker-compose.yml testwinsper
volumes:
- name: dependency
  host:
    path: /root/.m2
