version: "3"

services:
  winsper-server:
    image: winsper-server
    ports:
      - "7100:7100"
    volumes:
      - "/root/.m2"
    deploy:
      replicas: 1
      constraints: [node.role == manager]

  winsper-zuul:
    image: winsper-zuul
    ports:
      - "7120:7120"
    volumes:
      - "/root/.m2"
    deploy:
      replicas: 2
      placement:
        constraints: [node.role == manager]

  winsper-config:
    image: winsper-config
    ports:
      - "7199:7199"
    volumes:
      - "/root/.m2"
    deploy:
      replicas: 2

  winsper-user:
    image: winsper-user
    ports:
      - "7180:7180"
    volumes:
      - "/root/.m2"
    deploy:
      replicas: 3

  winsper-hean:
    image: winsper-hean
      ports:
        - "7190:7190"
      volumes:
        - "/root/.m2"
      deploy:
        replicas: 5

  winsper-admin:
    image: winsper-admin-service
      ports:
        - "7190:7190"
      volumes:
        - "/root/.m2"
      deploy:
        replicas: 2
